"""empty message

Revision ID: 10671722f1a0
Revises: 29b052ee87b4
Create Date: 2015-01-28 11:56:28.215945

"""

# revision identifiers, used by Alembic.
revision = '10671722f1a0'
down_revision = '29b052ee87b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jmeno', sa.String(), nullable=False),
    sa.Column('prijmeni', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_prijmeni', 'loguser', ['prijmeni'], unique=False)

    op.create_table('karty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_karty', sa.String(), nullable=False),
    sa.Column('datum_pristupu', sa.DateTime, nullable=False),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_id_zaznamu'),
    sqlite_autoincrement=True
    )
    op.create_index('id', 'id_karty',  unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loguser_prijmeni', table_name='loguser')
    op.drop_table('loguser')

    op.drop_index('id', 'id_karty',table_name='karty')
    op.drop_table('karty')
    ### end Alembic commands ###
